Comment icon position on hidden elements - WIP
storytouch/ep_comments pull request #19
Opened 2018-01-23 14:40 UTC by joassouza

2018-01-29 15:21 UTC, joassouza commented
Este PR é relativo a esse [card](https://trello.com/c/BV87IbHp/1174-esconder-%C3%ADcones-quando-elementos-n%C3%A3o-est%C3%A3o-vis%C3%ADveis). 
Acerta o posicionamento do ícone em elementos escondidos e mostra os scene marks não visíveis quando clicamos em um comentário que está aplicado nele. Para essa última regra é necessário que o comentário esteja somente no SM. Caso esteja, por exemplo, em um SM e heading, mostramos no heading e ao clicar no ícone nada acontece.

2018-01-29 17:48 UTC, lpagliari requested changes
Cara, ficou muito bom ter um módulo só para calcular a posição do ícone, bem mais claro assim. Dá até para mover o `commentIconsPosition` para dentro do `commentIcons`, já que só ele precisa saber que há essa "especialização". Neste caso, precisaria criar um `setYofComments()` no `commentIcons` que repasse a responsabilidade para o `commentIconsPosition`.

2018-01-29 17:48 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +var _ = require('ep_etherpad-lite/static/js/underscore');
Ótima idéia de extrair esse cara!! Ficou BEEEEEM melhor!

2018-01-29 17:48 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +  var targetLineIsVisible = $targetLine.get(0).getBoundingClientRect().height > 0;
sugestão para tentar fazer o menos de esforço possível enquanto pega a posição dos ícones: podemos verificar se o comentário está em uma linha visível sem ter que pegar a `$targetLine`? Digo, funcionaria verificar se `$target.get(0).getBoundingClientRect().height > 0`?

2018-01-29 17:48 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +  if (visibleLine) {
tem chance de `visibleLine` ser falsy?

2018-01-29 17:48 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +  // on scene marks spans are used in more places that the its text
acho que sobrou um `the` ou um `its` nesse comentário

2018-01-29 17:48 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +  var lineHasNotText = $textElement === undefined;
cara, acho que `first()` nunca retorna `undefined`...

2018-01-29 17:48 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
1. Por que precisa ser no SM title? Não pode ser no summary?
2. Se `$element` é a linha, sugiro chamar de `$line` então. Senão não fica claro que se trata da div, como no caso `[2]`

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/_utils.js
> +  addCommentAndReplyToLine: function(lines, textOfComment, textOfReply, done) {
precisa ajustar o nome da função tb, já que agora vc recebe lines. Ou então (melhor ainda) faz como te sugeri naquela vez milênios atrás: cria um 2o método `addCommentAndReplyToLine` que chama `addCommentAndReplyToLines([line], ...)`, para não ter que sair percorrendo o código mudando o nome da função.

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/_utils.js
> +  addCommentToLine: function(lines, textOfComment, done) {
idem

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/_utils.js
> +  waitForCommentToBeCreatedOnLine: function(lines, done) {
idem

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/_utils.js
> +  pressShortcutToAddCommentToLine(lines, done) {
idem

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +  var padId, firstCommentId, secondCommentId, thirdCommentId;
se vc chama de "first", "second", "third comment", não dá para saber qual a diferença entre eles. Mas chamando de "multi line comment" vc sabe na hora para que aquele comentário foi usado nos testes.

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +  var reloadPad = function(test, done) {
tem uma função que faz exatamente isso no `_utils`, acho que não precisa desta aqui. Precisa?

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +      apiUtils.startListeningToApiEvents();
se vc chamar a `utils.createPad` ao invés da `helper.newPad` na `createScript`, vc nem precisa chamar `startListeningToApiEvents`. Teve algum motivo para vc mudar isso no `before`?

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> -    });
1. faltou chamar a `testIfSendCommentIdOnAPI` aqui
2. se vc só vai testar se mandou o comment id na API aqui, talvez seja melhor nem extrair um método para isso. Deixa o teste apenas no lugar onde ele é necessário...

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +    var $lineOfCommentIcon = $lineWhereCommentShouldBe.find('.sceneMark--title > span, heading > span').first();
preciso pegar o span de dentro da linha? Não dá para usar o pai dele?

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +      apiUtils.startListeningToApiEvents();
mesma coisa nesse `before`: usa o método do `utils` para criar o pad que ele já chama `startListeningToApiEvents`

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +      ep_script_toggle_view_test_helper.utils.setEascMode(['script','scene', 'sequence', 'act', 'episode']);
sugestão: usa o `ep_script_toggle_view_test_helper.utils.enableAllEASCButtons()`

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +    utils.resetScreenSize();
fez resize do frame mesmo?

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +      });
sugestão, para ficar mais fácil de rodar os testes e saber como o EASC está em cada teste: ou vc chama `setEascMode()` antes de cada contexto -- e neste caso não precisa habilitar todos os níveis no `before`, como vc fez --, ou em cada `before` que vc mudar o EASC, vc cria um `after` que volta a habilitar todos os níveis do EASC. Isso garante que no começo de cada `context` o EASC está sempre mostrando tudo, e assim fica mais fácil montar os passos de cada teste

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +    context('and it is hidden', function() {
já que não tem outro `context` para se opor ao `and it is hidden`, dá para simplificar a estrutura desse teste e juntar os dois contextos em um só: `context('when has comment on a hidden scene mark', function() {...`

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +          done();
cara, esse teste aí em cima eu fiquei confusa: é para ter 2 ícones, é isso? Um para o comentário que de fato está na linha do ATO, e outro para o comentário que está no EPI mas é mostrado no ATO. É essa a idéia?

2018-01-29 17:48 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +            done();
boa! Demorei um pouco para entender o cenário que vc montou, mas foi um ótimo "catch" seu!

2018-01-29 18:03 UTC, joassouza commented on static/js/commentIconsPosition.js
> +  if (visibleLine) {
se não tiver nada visível, por exemplo (nem script nem sm)

2018-01-29 18:08 UTC, joassouza commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
1. Isso merece um comentário ficou meio obscuro mesmo. Se tem um SM escondido, a gente vai procurar o próximo visível (sempre será um _SM title_). Caso seja um SE escondido, a mesma coisa se aplica. Não tem como o próximo elemento visível ser um _summary_ e não um _title_.
2. Ótimo!

2018-01-29 20:36 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +  if (visibleLine) {
e o que acontece se a gente chamar `this._getPositionOfFirstTextElementOnSMtitleOrHeading($(visibleLine));` com `visibleLine` falsy? Retorna zero?

Se sim, eu diria até para tirar o `if`, para ficar mais direto.

2018-01-29 20:38 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
sobre o 1: se o comentário começar em um summary, deveria retornar a posição do summary, não?

2018-01-29 20:56 UTC, joassouza commented on static/tests/frontend/specs/commentIcons.js
> +  var reloadPad = function(test, done) {
no `_utils`, o `padId` é guardado quando cria o pad globalmente

2018-01-29 20:58 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +  var reloadPad = function(test, done) {
mas pq isso é um problema? O padId do utils vai estar atualizado com o valor que vc quer fazer reload

2018-01-29 21:03 UTC, joassouza commented on static/tests/frontend/specs/commentIcons.js
> +  var reloadPad = function(test, done) {
true! vi aqui agora!

2018-01-29 21:05 UTC, joassouza commented on static/tests/frontend/specs/commentIcons.js
> +      apiUtils.startListeningToApiEvents();
eu preciso criar um script que tenha SM para os testes. A `utils.createPad` cria um script com dois generals

2018-01-29 21:05 UTC, joassouza commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +    var $lineOfCommentIcon = $lineWhereCommentShouldBe.find('.sceneMark--title > span, heading > span').first();
dá diferença de altura

2018-01-29 21:08 UTC, joassouza commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +          done();
exatamente!

2018-01-29 21:12 UTC, joassouza commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +      apiUtils.startListeningToApiEvents();
aqui é o mesmo caso do texto fixo que tem no `utils`

2018-01-29 21:21 UTC, joassouza commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
se a `$targetLine` é um `summary` quer dizer que a gente tem um comentário em um SM que está *escondido* é um `summary`. Então a gente tem que procurar qual elemento que deveria ser posto um ícone de comentário.

2018-01-29 21:26 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +      apiUtils.startListeningToApiEvents();
Entendi. Hum, tô pensando aqui... Não gosto de vc ter que ficar lembrando de chamar a `startListeningToApiEvents`, não tem nada a ver com os testes.
Sugestão: passa o conteúdo do roteiro como último parâmetro na `createPad` (vai ter que passar também para a `_createOrResetPadText`). Se não tiver nada nesse parâmetro, usa o `'something<br>anything'` atual, senão usa o que vc passar. O que acha?
Ou então cria o roteiro com esses dois generals e depois faz as tuas mudanças. Melhor que ficar chamando a `startListeningToApiEvents`, não?

2018-01-29 21:27 UTC, joassouza commented on static/tests/frontend/specs/commentIcons.js
> +      apiUtils.startListeningToApiEvents();
Blz, vou refatorar a função do utils

2018-01-29 21:28 UTC, lpagliari commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +    var $lineOfCommentIcon = $lineWhereCommentShouldBe.find('.sceneMark--title > span, heading > span').first();
tem a margem, né? Blz, entendi

2018-01-29 21:28 UTC, joassouza commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +    utils.resetScreenSize();
removi!

2018-01-29 21:32 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
Hum, entendi. Tinha me perdido aqui, não me dei conta que só entrava aqui quando a linha original estava escondida.

2018-01-29 21:34 UTC, lpagliari commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
Talvez simplificando o nome da função ajude... Não precisamos saber muito o que ela faz nas entranhas do código, só precisamos saber que ela vai pegar a altura da próxima linha visível -- é isso que ela faz, certo? `_getPositionOfFirstVisibleTextElementAfterTarget`

2018-01-29 21:38 UTC, joassouza commented on static/js/commentIconsPosition.js
> +commentIconsPosition.prototype._getPositionOfFirstTextElementOnSMtitleOrHeading = function($element) {
Achei ótimo o nome. Confesso que já troquei esse nome umas 6 vezes. Por isso que toda função nasce `stuff` ou `thing` lol

2018-01-30 14:15 UTC, joassouza commented on static/tests/frontend/specs/iconPositionOnHiddenElements.js
> +      });
eu mostrei todos os elementos `ep_scene_navigator_test_helper.utils.enableAllEASCButtons();` por que preciso adicionar comentários nos scene marks que estão escondidos.

2018-01-31 14:52 UTC, lpagliari requested changes
Mais algumas observações que eu fiz, além do que já discutimos no Slack

2018-01-31 14:52 UTC, lpagliari commented on static/js/textMarkIconsPosition.js
> +  var targetLineIsVisible = $target.get(0).getBoundingClientRect().height > 0;
vi que vc moveu o `$targetLine` para dentro do `if`. Faltou renomear o `targetLineIsVisible` :)

2018-01-31 14:52 UTC, lpagliari commented on static/js/textMarkIconsPosition.js
> +  var $textElement = $line.find('.sceneMark--title, heading').find('span').first(); // [1]
essa linha aqui pode dar problema, se formos usar este módulo em outros casos. Será que não seria melhor pegar o 1o nodo com texto direto? Tem uma solução para fazer isso [aqui](https://stackoverflow.com/a/6520267/7884942).

2018-01-31 17:16 UTC, joassouza commented on static/js/textMarkIconsPosition.js
> +  var $textElement = $line.find('.sceneMark--title, heading').find('span').first(); // [1]
só lembrando que o `<br>` não é um textNode, então teríamos que fazer a mesma coisa, o segundo `if (lineHasNotText)`

2018-01-31 17:20 UTC, lpagliari commented on static/js/textMarkIconsPosition.js
> +  var $textElement = $line.find('.sceneMark--title, heading').find('span').first(); // [1]
Sim, sim, minha sugestão era só para não depender do `'.sceneMark--title, heading'` nem do `'span'`. O `br` não tem jeito mesmo...

2018-01-31 19:56 UTC, merged