[feat] Allow multiple comments on same range
storytouch/ep_comments pull request #31
Opened 2018-04-30 15:18 UTC by joassouza

Com este PR a gente permite adicionar mais de um comentário em um mesmo trecho do texto. 
[Trello](https://trello.com/c/SUFzBIbC/172)

2018-04-30 19:34 UTC, lpagliari requested changes

2018-04-30 19:34 UTC, lpagliari commented on static/js/commentSaveOrDelete.js
>    var attributeValue = commentId;
Algum motivo para não usar apenas `true`/`false` como valor? Não cheguei a olhar o código todo, imagino que isso possa ser útil em outro lugar...

2018-04-30 19:34 UTC, lpagliari commented on static/js/index.js
> +    if(context.key.startsWith(shared.COMMENT_PREFIX) && context.value !== "comment-deleted") {
Fiquei um pouco com medo de estarmos usando apenas `c-` como prefixo aqui -- medo de dar conflito com outro atributo. Acha muito arriscado?

2018-04-30 19:34 UTC, lpagliari commented on static/tests/frontend/specs/api-dataChanged.js
> +      });
Fiquei pensando aqui sobre esses testes... Embora não tenha um arquivo melhor para colocá-los (dentre os existentes), eu achei que eles aqui não tinham muito a ver com a parte da API que manda updates dos dados. Quem sabe cria um arquivo específico para os testes de dois comentários no mesmo trecho, que tal?

Esse `_.times(6, utils.undo);`, por exemplo, acabou sendo necessário pq estamos tentando aproveitar testes que não tem muito a ver com o que a gente está testando aqui.

2018-04-30 19:34 UTC, lpagliari commented on static/tests/frontend/specs/api-dataChanged.js
> +        expect(comments.length).to.be(2);
Acho importante testar os dados mandados, mesmo que só uma parte deles (o texto do comentário, por ex). Assim evitamos bugs como estarmos mandando um comentário deletado, ou 2x o mesmo comentário.

2018-04-30 19:34 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +  // here we create a new clean pad to reset the previous state that simulates two pages
2 páginas?

2018-04-30 19:34 UTC, lpagliari commented on static/tests/frontend/specs/commentIcons.js
> +        // we create a comment so we create a second one that wraps the first one
Boa!! 👍

2018-04-30 19:34 UTC, lpagliari commented on static/js/commentDataManager.js
> +  $commentsOnText.each(function() {
não dá para usar `map` ao invés de `each`? É mais direto...

2018-04-30 19:34 UTC, lpagliari commented on static/js/commentDataManager.js
> +  // go to a function maybe we call it on _getListOfCommentsOrdered
não entendi o comentário dessa linha aqui...

2018-04-30 19:34 UTC, lpagliari commented on static/js/commentDataManager.js
> +commentDataManager.prototype._getSceneNumber = function ($scenes, nodeWithComment) {
ficou bem melhor extrair para essa função! 👍

2018-04-30 19:34 UTC, lpagliari commented on static/js/commentDataManager.js
> +    var isAReplyIdOfThisComment = isAReplyId && commentData.replies[className];
Talvez seja uma boa fazer o teste com comentários + replies, assim testa essa parte tb (se eu entendi direito o que essa parte faz, hehe)

2018-04-30 22:09 UTC, joassouza commented on static/js/commentDataManager.js
> +  // go to a function maybe we call it on _getListOfCommentsOrdered
era para remover isso, era parte de umas anotações que eu tinha feito

2018-04-30 22:09 UTC, joassouza commented on static/js/commentDataManager.js
> +    var isAReplyIdOfThisComment = isAReplyId && commentData.replies[className];
essa parte não é muito claro mesmo. Eu removi esse código de uma função e coloquei aí. Na verdade, meus planos é mudar um pouco essa lógica. Se eu conseguir fazer aquela otimização que nós falamos se brincar nem precisará disso

2018-04-30 22:09 UTC, joassouza commented on static/tests/frontend/specs/commentIcons.js
> +  // here we create a new clean pad to reset the previous state that simulates two pages
tá errado. Era para _dois usuários editando o mesmo script_

2018-04-30 22:09 UTC, joassouza commented on static/tests/frontend/specs/api-dataChanged.js
> +      });
Eu concordo viu. Eu tive o mesmo feeling quando comecei a _procurar lugar_ para colocar os testes dessa feature

2018-04-30 22:09 UTC, joassouza commented on static/js/index.js
> +    if(context.key.startsWith(shared.COMMENT_PREFIX) && context.value !== "comment-deleted") {
vou colocar uma condição mais forte no if, tipo usar uma regex para validar se é o atributo

2018-04-30 22:09 UTC, joassouza commented on static/js/index.js
> +    if(context.key.startsWith(shared.COMMENT_PREFIX) && context.value !== "comment-deleted") {
um conflito de atributo seria um bug muito, muito tenso de encontrar se acontecesse. Melhor adotar um approach mais defensivo mesmo

2018-04-30 22:09 UTC, joassouza commented on static/js/commentSaveOrDelete.js
>    var attributeValue = commentId;
não tive motivo, deixei o valor do jeito que estava. Pensando bem, não faz sentido mesmo deixar o commentID como o valor do atributo. Vou mudar

2018-04-30 22:09 UTC, joassouza commented on static/js/commentDataManager.js
> +  $commentsOnText.each(function() {
acho que usei o `each` por que poderia ter mais de um comentário por trecho o que BTW  não faz nenhum sentido 😒 . O próprio `map` daria conta já que faço o `flatten` depois de executar esse trecho

2018-05-02 12:22 UTC, lpagliari commented on static/js/commentSaveOrDelete.js
>    var attributeValue = commentId;
antes de vc fazer a mudança para `true`/`false`, talvez seja bom ver a coisa do nome do atributo ser mais do que apenas `c-...`. Se vc usar um prefixo, por ex, dá para deixar o `commentId` no valor mesmo, assim não precisa fazer parse do nome do atributo quando precisar pegar o `commentId` de novo.

2018-05-02 20:47 UTC, merged