[fix] Avoid ghost comments
storytouch/ep_comments pull request #36
Opened 2018-08-13 20:26 UTC by joassouza

This PR adds two new behaviours:

1. It validates if comment has text field not empty, when adding in bulk
2. Avoid sending a comment to Teksto via internal API, if its data is not valid. E.g. There's a comment id on script but its data is not saved on the db (ghost comment).
[Trello 1477](https://trello.com/c/1ds2eEaH/1477-p3-coment%C3%A1rios-n%C3%A3o-mostrar-coment%C3%A1rios-fantasmas)

2018-08-13 21:27 UTC, lpagliari requested changes
Não deveríamos testar tb o caso no frontend? Mesmo sendo _gambi_ adicionar o `commentId` direto no DOM, vc teria alguma outra sugestão para simular o comportamento do bug que vc corrigiu? Eu acho que vale a pena, dado que surgiu um comentário fantasma e nós resolvemos ser precavidos com isso. *Como* ele surgiu a gente não sabe, mas *o que fazer com isso* a gente decidiu. Ter o teste de frontend simularia esse problema, ao meu ver.

2018-08-13 21:27 UTC, lpagliari commented on commentManager.js
> +        return '';
acho que nem precisa desse último cara, precisa? O `compact` já vai remover, sendo `''` ou `undefined`

2018-08-13 21:27 UTC, lpagliari commented on static/js/commentDataManager.js
> +      var existTargetComment = !(_.isEmpty(targetComment))
Além de verificar se `targetComment !== undefined`, isso aqui pega que outro caso?

2018-08-13 21:27 UTC, lpagliari commented on static/js/commentDataManager.js
> +      var existTargetComment = !(_.isEmpty(targetComment))
Digo, pq precisa de uma validação tão complicada como `_.isEmpty(targetComment)`?

2018-08-13 21:27 UTC, lpagliari commented on static/js/commentDataManager.js
> +      return {};
aqui é o mesmo caso do `commentManager.js`, acho que dá para vc não retornar nada -- e ainda de quebra pode usar o `compact` ao invés do `filter`

2018-08-13 21:27 UTC, lpagliari commented on static/js/commentDataManager.js
> +      var existTargetComment = !(_.isEmpty(targetComment))
Outro ponto: se o comentário tiver id, mas não tiver texto, isso deveria passar? Não estou dizendo que precisa validar todos os campos, mas levantei essa hipótese para vc ter usado `_.isEmpty(targetComment)` para tentar pegar o maior no. de casos possível...

2018-08-13 21:27 UTC, lpagliari commented on static/tests/backend/specs/api/comments.js
> +var addCommentsOnBulk = function(socket, padId, commentData, cb) {
`addCommentsInBulk`

2018-08-14 13:27 UTC, joassouza commented on static/js/commentDataManager.js
> +      return {};
ótima sugestão!

2018-08-14 17:54 UTC, joassouza commented
@lpagliari adicionei o teste que vc sugeriu

2018-08-14 18:25 UTC, merged