[feat] Float comment window
storytouch/ep_comments pull request #40
Opened 2018-11-22 18:02 UTC by joassouza

This is the first implementation of the feature that allows showing the comment info dialog **(CIG)** on the Editor.
When user clicks in a comment icon and the support column is minimized, it shows the CIG on the Editor body.

### New behaviors 

- [x] edit comment on CIG

- [x] remove comment on CIG

- [x] listen to event from Teksto that informs when it should display the CIG

### Future Work

- [ ] display more info on CIG (author, date, etc)

- [ ] show length of replies

- [ ] show replies text

- [ ] add replies

- [ ] reuse the code that controls the CIG on ep_touches

- [ ] improvements on UI/UX

Requires https://github.com/storytouch/web/tree/feat/text-marks-display-handler to work.

For more details [trello](https://trello.com/c/84i3zRkJ/1056-p3-coment%C3%A1rios-aplicar-melhorias-das-janelas-flutuantes-j%C3%A1-implementada-nas-tags-para-os-coment%C3%A1rios)

2018-11-22 18:02 UTC, joassouza commented
@lpagliari vou usar essa branch como base para as próximas branches.

2018-11-23 20:39 UTC, lpagliari requested changes
Cara, **MUITO** bom esse PR!! Vc conseguiu montar uma base bem limpa e clara (me pareceu) sobre as mudanças, acho que vai facilitar muito os próximos PRs dessa funcionalidade.

Sei que a parte do info dialog é meio complexa pq tem muita customização passando de um lado para o outro (eu sempre me perco tentando entender onde vai parar cada parte), mas assumindo que as modais estão configuradas direitinho, fica fácil construir novas funcionalidades em cima disso.

Muito bom PR! Ótima forma de terminar a semana :-)

2018-11-23 20:39 UTC, lpagliari commented on static/js/commentIcons.js
> +  var commentDataManager = pad.plugins.ep_comments_page.commentDataManager;
dá para usar o `thisPlugin` aqui tb

2018-11-23 20:39 UTC, lpagliari commented on static/js/copyPasteEvents.js
> -  pad.plugins.ep_comments_page.fakeIdsMapper = fakeIdsMapper.init();
o `fakeIdsMapper` só é usado para o copy-paste... A idéia aqui era deixar todas as inicializações em um lugar só, é isso?

2018-11-23 20:39 UTC, lpagliari commented on static/js/index.js
> +  return [preTextMarker.MARK_TEXT_EVENT, preTextMarker.UNMARK_TEXT_EVENT, textMarkInfoDialog.NON_SCROLLABLE_EVENT];
melhor chamar o `NON_SCROLLABLE_EVENT` de um nome que explique mais o que ele faz, como nos outros eventos que definimos que não são "scrolláveis". Assim dá para entender o motivo desse cara existir e estar sendo passado aqui, eu acho...

Pensei em algo como `SELECT_TEXT_OF_COMMENT`, ou algo nessa linha... Veja o que vc acha que fica melhor.

2018-11-23 20:39 UTC, lpagliari commented on static/js/utils.js
> +// and use this one
boa!

2018-11-23 20:39 UTC, lpagliari commented on templates/comments.html
> +      </div>
Uma dúvida, que talvez o resto do código responda depois (ainda não vi tudo): vc não está mostrando o autor do comentário na modal? Acho que precisaria...

2018-11-23 20:39 UTC, lpagliari commented on static/tests/frontend/specs/api-showCommentInfo.js
> +        return helper.padOuter$('#text-mark-info').is(':visible');
seria bom tb verificar se as informações do comentário estão sendo mostradas corretamente na modal

2018-11-23 20:39 UTC, lpagliari commented on static/tests/frontend/specs/workflowToEditComment.js
> +      openCommentEditDialog(test, done);
como esse é um método para testar algo, melhor chamar de `testIfCommentEditDialogIsOpened`. Senão, chamando de `openCommentEditDialog`, fica parecendo que vc vai de fato *abrir* o CED

2018-11-23 20:39 UTC, lpagliari commented on static/tests/frontend/specs/workflowToEditComment.js
> +      closeCommentInfoDialog(done);
idem aqui, melhor renomear para `test...`

2018-11-23 20:39 UTC, lpagliari commented on static/tests/frontend/specs/workflowToEditComment.js
> +      it('opens the Comment info dialog with the updated description', function(done) {
boa!!

2018-11-23 20:39 UTC, lpagliari commented on static/tests/frontend/specs/workflowToEditComment.js
> +  // assume dialogs are opened
bom comentário! E bons métodos auxiliares tb, deixou o código bem mais limpo

2018-11-23 20:39 UTC, lpagliari commented on static/tests/frontend/specs/workflowToRemoveComment.js
> +  };
ambos os métodos foram definidos no outro teste tb. Melhor movê-los para o `utils` dos testes.

2018-11-23 20:39 UTC, lpagliari commented on static/js/index.js
> +  return [preTextMarker.MARK_TEXT_EVENT, preTextMarker.UNMARK_TEXT_EVENT, textMarkInfoDialog.NON_SCROLLABLE_EVENT];
Vi aqui que o evento já tinha esse nome no ep_tags. Se quiser deixar com esse nome por enquanto, para facilitar enquanto os arquivos estão duplicados, não vejo problema. Podemos renomear a variável depois, quando o código estiver mais estável e limpo.

2018-11-23 20:39 UTC, lpagliari commented on static/js/textMarkInfoDialog.js
> +};
aaaaaaacho que esse cara não é mais usado (fiz uma busca aqui e não achei nada). Eu colocaria um `TODO` aqui para revisar isso depois

2018-11-23 20:39 UTC, lpagliari commented on static/js/textMarkInfoDialog.js
> +var textMarkInfoDialog = function(props) {
cara, ficou MUITO bom esse módulo!!! 👏 Sei que vc copiou uma parte do ep_tags, mas mesmo assim foi muito bacana a maneira que vc deixou partes customizáveis. Ótimo código!!

2018-11-23 20:39 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  this.showCommentInfoForId = this.showCommentInfoForId.bind(this);
hum, esse `bind` ficou meio estranho aqui, não fica claro pq ele é necessário dentro desse módulo... 

Imagino que vc tenha precisado dele pq centralizou as definições dos callbacks da API no `index.js`, certo? Nesse caso, será que não faria mais sentido fazer o `bind` lá?

2018-11-26 10:43 UTC, joassouza commented on static/js/copyPasteEvents.js
> -  pad.plugins.ep_comments_page.fakeIdsMapper = fakeIdsMapper.init();
o fakeId é usado dentro do `shared.js` também. Eu gostei bastante do padrão que você adotou no ep_touches. Tudo centralizado, somente um lugar para controlar quem inicia primeiro

2018-11-26 10:45 UTC, joassouza commented on static/js/index.js
> +  return [preTextMarker.MARK_TEXT_EVENT, preTextMarker.UNMARK_TEXT_EVENT, textMarkInfoDialog.NON_SCROLLABLE_EVENT];
ótimo! Acho que fica mais fácil deixando igual para perceber onde devemos mudar depois. A ideia é ter o mesmo nome para `comments e tags`.

2018-11-26 10:47 UTC, joassouza commented on templates/comments.html
> +      </div>
Sim, precisa. Além disso talvez data também. Eu deixei essa adição mais pra frente

2018-11-26 10:48 UTC, joassouza commented on static/tests/frontend/specs/api-showCommentInfo.js
> +        return helper.padOuter$('#text-mark-info').is(':visible');
Sim, tem um conjunto de teste no próximo PR que checa essas informações adicionais (descrição). Deixei nesse teste só a validação da API.

2018-11-26 10:48 UTC, joassouza commented on static/tests/frontend/specs/api-showCommentInfo.js
> +        return helper.padOuter$('#text-mark-info').is(':visible');
Talvez fique um teste meio repetido... 🤔

2018-11-26 10:49 UTC, joassouza commented on static/tests/frontend/specs/workflowToEditComment.js
> +      openCommentEditDialog(test, done);
boa!

2018-11-26 12:26 UTC, joassouza commented on static/js/textMarkInfoDialog.js
> +};
boa!

2018-11-26 13:14 UTC, joassouza commented on static/js/commentInfoDialog.js
> +  this.showCommentInfoForId = this.showCommentInfoForId.bind(this);
é desnecessário esse `bind` aí. Eu removi 👍

2018-12-19 11:48 UTC, lpagliari approved these changes
LGTM

2018-12-19 11:52 UTC, merged