[feat] Show, edit, delete replies using dialog on editor
storytouch/ep_comments pull request #41
Opened 2018-12-04 18:02 UTC by joassouza

This PR addresses the implementation of the reply dialog. 

### New behaviors

1. Render replies dialog
2. Add more information on the comment dialog
3. Add button to show replies
4. Change the text of this button to "hide replies" when the reply window is visible
5. Implement the edition of replies using the popup dialog
6. Implement the deletion of replies using the popup dialog

Trello: https://trello.com/c/84i3zRkJ/1056-p3-coment%C3%A1rios-aplicar-melhorias-das-janelas-flutuantes-j%C3%A1-implementada-nas-tags-para-os-coment%C3%A1rios

`*`: The file `static/css/commentDialog.css` will be used to style the dialogs

Example of a comment with visible replies
![screen shot 2018-12-04 at 3 54 17 pm](https://user-images.githubusercontent.com/4945372/49462316-e6180600-f7dc-11e8-856f-a01331a03464.png)

Example of a comment with collapsed replies
![screen shot 2018-12-04 at 3 55 47 pm](https://user-images.githubusercontent.com/4945372/49462417-21b2d000-f7dd-11e8-942f-70ca0e499ad9.png)

2018-12-04 19:18 UTC, lpagliari requested changes
Ufa! 😅 Esse foi grande! Muito bom, cara, está ficando bem boa essa feature

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentDataManager.js
> +  var comment = this.commentsStillOnText.filter(function(comment){
O `commentsStillOnText` é um mapa `commentId` => `commentData`? Ou é um array?

Eu achei que fosse array, mas como vc inicializou ele com `{}`, fiquei na dúvida.

Se for um mapa, ao invés do `filter` vc pode usar direto `this.commentsStillOnText[commentId]` para pegar os dados do comentário.

2018-12-04 19:18 UTC, lpagliari commented on templates/comments.html
> +          class="button button--save reply-button--cancel"
acho que é `button--cancel`, né?

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/_utils.js
> +  closeCommentWindowAndClickOnShowReplies: function(commentLine, cb) {
acho melhor chamar de `reloadCommentWindowAnd...` ou `reopenCommentWindowAnd...`. Eu li `closeCMAnd...` e fiquei pensando como ele ia clicar no "show replies" se a janela tinha sido fechada, hehehe

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/_utils.js
> +  closeCommentWindowAndClickOnShowReplies: function(commentLine, cb) {
Aliás, esse método aqui não deveria ser necessário no futuro, certo? Imagino que para ter o dado mais atual da janela eu não devesse precisar recarregá-la -- viria automaticamente, da mesma forma que estamos sincronizando as demais janelas.

A idéia é fazer isso no futuro?

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/commentInfo.js
> +  var DATE_TIME_REGEX = /((0[1-9]|[12]\d|3[01])\/([1-9]|1[0-2])\/[12]\d{3})(, ([0-9]|1[0-2]):[0-9][0-9] (A|P)M)/;
hum, isso aqui tem grande chance de encher nosso saco no longo prazo. O melhor nesse caso é:

- mudar a data do comentário na mão (todos eles são armazenados no `helper.padChrome$.window.pad.plugins.ep_comments...`, eu acho), para termos um teste com data fixa;

- fixar tb o locale. Neste caso, vc pode setar uma prop do plugin com o locale (inicializa com `window.navigator.language`, mas no teste sobrescreve para usar o que vc quer). Roubei a idéia [daqui](https://stackoverflow.com/questions/42218386/javascript-tolocalestring#comment71598199_42218386)

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/commentInfo.js
> +  };
Hum, legal essa idéia do `REPLY_FIELDS`!

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/commentInfo.js
> +  };
Tenho tentado mover métodos para o fim dos testes (quando dá, né?), assim deixa o começo mais focado no teste em si. Em geral métodos que são rodados dentro dos `it` podem ser movidos pro fim; já os que contêm `context` e `it` dentro deles precisam vir antes (pois usamos esses caras nas declarações dos testes).

Se quiser adotar esse padrão, esses dois caras aqui poderiam ir pro fim.

(Aliás, se tiver alguma sugestão para a gente organizar melhor os testes do Etherpad, é só falar. Temos uns 3 ou 4 jeitos diferentes de organizar atualmente 😒 )

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/commentInfo.js
> +    expect(getTextOfDescriptionHeader('scene')).to.be('SCENE 0');
não sei se é algo que precisa ser muito testado, já que pode ter vindo de outro lugar. Mas testar na cena 0 pode ser um viés do teste. Se for um código realmente novo (e não tiver outro teste pra isso), sugiro criar outras cenas no roteiro de teste

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/commentInfo.js
> +    it('displays the length of replies', function(done) {
boa!!

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/commentInfo.js
> +});
ótimos testes!! 👍

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/workflowToEditReply.js
> +});
Eu lembro que vc comentou que poderia haver duas respostas sendo editadas ao mesmo tempo. É um cenário que precisaria ser testado, ou do jeito que está esses testes já cobrem?

Não vejo problema em não ter esse teste, só chamo a atenção para esse cenário pq sei que pode ser meio chatinho...

2018-12-04 19:18 UTC, lpagliari commented on static/tests/frontend/specs/workflowToRemoveReply.js
> +    });
acho que se extrairmos um helper com toda essa parte já simplificaria os testes da janela flutuante, né? Tipo um arquivo com métodos para criar o roteiro com todos os comentários e replies que queremos + constantes (ex: `COMMENT_AND_REPLIES_LINE`) para usarmos nos arquivos de teste.

Vi esse método para criar o mesmo roteiro (me pareceu o mesmo, pelo menos) e pensei nisso...

2018-12-04 19:18 UTC, lpagliari commented on static/js/textMarkInfoDialog.js
> +  infoDialogCustomButtons: array of objects with additional buttons to show on info dialog window (optional)
coloca tb o formato desses caras. (Acho que é ` { buttonName: String, handler: function, buttonL10nArgs: String }`, certo?)

2018-12-04 19:18 UTC, lpagliari commented on static/js/textMarkInfoDialog.js
> +textMarkInfoDialog.prototype._buildButton = function(props) {
boa!

2018-12-04 19:18 UTC, lpagliari commented on static/js/textMarkInfoDialog.js
> +  infoDialogCustomButtons: array of objects with additional buttons to show on info dialog window (optional)
Ah, e tb qual a assinatura do `handler`. Ajuda a não termos que sair caçando o código disso no meio desse arquivo

2018-12-04 19:18 UTC, lpagliari commented on static/js/textMarkInfoDialog.js
> +    self._fillTextMarkContentOnInfoDialog(self.addAdditionalElementsOnInfoDialog);
como vc guarda o `addAdditionalElementsOnInfoDialog`, nem precisaria passá-lo como parâmetro, certo? Daria para pegá-lo direto on de vc for usar...

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  event.preventDefault(); // avoid reloading the editor
boa! 👍

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +    this.thisPlugin.api.onReplyEdition(targetData.commentId, replyId, newReplyText);
não seria melhor esperar com o formulário aberto enquanto salva no banco, e só depois (no callback) carregar a info dialog? Assim vc garante que só vai mostrar a informação já salva.

Daria, inclusive, para passar essa parte de gerar a data para o lado do servidor (que é o que me parece mais correto, aliás).

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  return $infoReplyDialog.find(REPLY_DESCRIPTION_BODY_CLASS).text();
precisa do `children()` na linha anterior? Não daria para chamar o `find()` direto no `$replyContainer`? Fiquei com a impressão que as duas formas fariam a mesma coisa...

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  event.preventDefault(); // avoid reloading the page
aaaaaacho que esse cara não precisa. Só o `submit` precisaria...

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  commentL10n.localize($showOrHideRepliesButton); // [2]
uma idéia (é apenas uma sugestão, para mim ficou bom do jeito que está tb): ter um botão de exibir e um de esconder as respostas. Assim é só questão de mostrar um botão e esconder o outro, ao invés de ter que mudar o label e fazer a tradução toda vez.

Mas é só uma sugestão mesmo...

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  return userInitials.toUpperCase();
o `utils` tem algo bem parecido (`getUserInfo`), daria para mover esse cara pra lá e usá-lo dentro da `getUserInfo` para montar as iniciais

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  var comment = this.thisPlugin.commentDataManager.getDataOfCommentIfStillPresentOnText(commentId);
faz sentido a gente montar todo o resto se o comentário não estiver mais no texto?

2018-12-04 19:18 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +// this function receives a date in timestamp and returns in a format like "12/3/2018, 2:48 PM"
ótimo comentário!!

2018-12-04 20:33 UTC, joassouza commented on static/js/commentDataManager.js
> +  var comment = this.commentsStillOnText.filter(function(comment){
verdade! É um array. Vou mudar a inicialização

2018-12-04 20:35 UTC, lpagliari commented on static/js/commentDataManager.js
> +  var comment = this.commentsStillOnText.filter(function(comment){
nesse caso, melhor usar o [`find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) ao invés do `filter`

2018-12-04 20:39 UTC, joassouza commented on static/tests/frontend/specs/commentInfo.js
> +    expect(getTextOfDescriptionHeader('scene')).to.be('SCENE 0');
minha ideia aqui foi assegurar que tem o campo cena no `dialog`. Esse dado já vem pronto

2018-12-04 21:04 UTC, joassouza commented on static/js/commentInfoDialog.js
> +  return userInitials.toUpperCase();
boa!

2018-12-05 12:49 UTC, joassouza commented on static/tests/frontend/specs/_utils.js
> +  closeCommentWindowAndClickOnShowReplies: function(commentLine, cb) {
como conversamos, vou deixar isso como tarefa futura. Vou adicionar aqui no PR isso

2018-12-05 13:38 UTC, joassouza commented on static/tests/frontend/specs/workflowToEditReply.js
> +});
Olha do jeito que está não é um problema pq a gente monta as janelas usando as informações do _client side_. Quando a gente tiver a lógica de montar a janela depois da resposta do backend, acho que seria um bom cenário para testar. Tem mais cenários que deverão ser testados (responsa lenta, fechar a janela antes de acabar o loading, etc )

2018-12-05 13:40 UTC, joassouza commented on static/js/commentInfoDialog.js
> +    this.thisPlugin.api.onReplyEdition(targetData.commentId, replyId, newReplyText);
como acordamos, está como trabalho futuro

2018-12-05 14:54 UTC, joassouza commented on static/tests/frontend/specs/workflowToRemoveReply.js
> +    });
deixei bemmm menor!

2018-12-05 17:17 UTC, merged