[feat] Add replies
storytouch/ep_comments pull request #42
Opened 2018-12-10 16:28 UTC by joassouza

In this PR we build the UI to add replies to comments. 

### New Behavior
We have some special behaviors when user adds a reply
1. When comment does not have replies, after adding one, we show the reply
2. When comment has replies and they're visible we keep the reply dialog visible
3. When comment  has replies and they're not visible, we keep the reply dialog invisible and update the length of replies on the button that toggles the reply dialog.
4. When user clicks on the field to add a reply it increases its size and shows "cancel, save" button.

![dec-10-2018 14-25-35](https://user-images.githubusercontent.com/4945372/49746064-8364b580-fc87-11e8-9a72-b304f2760e6a.gif)

2018-12-11 18:51 UTC, lpagliari requested changes
Bom conjunto de testes, me parece testar bem todas aquelas combinações de cenários após criar a resposta. Só fiquei em dúvida quando à independência deles, caso eu queira rodar só uma parte dos contextos.

2018-12-11 18:51 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  }
cara, esse fluxo aqui ficou meio estranho... Em alguns casos chamamos `$repliesContainer.toggleClass` 2x. Não seria melhor uma chamada única? Isso tornaria mais fácil entender como vai ficar a visibilidade do elemento ao final do método.

2018-12-11 18:51 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +  this._updateToggleRepliesButton($toggleReplyButton, replyContainerIsVisible);
se vc não vai usar nem o `$toggleReplyButton` nem o `replyContainerIsVisible` neste método, melhor mover esses caras pra dentro do `_updateToggleRepliesButton` e passar apenas o `$repliesContainer`

2018-12-11 18:51 UTC, lpagliari commented on static/js/commentInfoDialog.js
> +commentInfoDialog.prototype._addAnswerCommentField = function($infoDialog, commentData) {
aqui `answer` seria `reply`? :-)

2018-12-11 18:51 UTC, lpagliari commented on static/js/index.js
> +      if (cb) cb();
👍

2018-12-11 18:51 UTC, lpagliari commented on static/tests/frontend/specs/workflowToAddReplies.js
> +      context('and comment already has replies', function() {
cara, isso aqui vai funcionar se eu rodar apenas esse contexto? Ou ele precisa do contexto anterior (que salva a 1a reply) para os testes passarem?

2018-12-12 14:38 UTC, joassouza commented on static/tests/frontend/specs/workflowToAddReplies.js
> +      context('and comment already has replies', function() {
bem lembrando! Mudei aqui

2018-12-12 16:29 UTC, merged