[feat] Send API message whenever a comment is added or deleted
storytouch/ep_comments pull request #58
Opened 2019-04-18 22:13 UTC by lpagliari

Send an API message `comments_set_changed` when the set of comments on pad changes. This includes:

- adding a comment to a text;
- deleting a comment from text;
- deleting text which has a comment;
- pasting text which has comments;
- UNDO and REDO operations that add/remove comment on text;

Implement part of https://trello.com/c/pp2UnQ1B/1828.

2019-04-22 16:57 UTC, joassouza requested changes

2019-04-22 16:57 UTC, joassouza commented on static/js/commentsSetChangeHandler.js
> +//  current user
ficou um espacinho aqui

2019-04-22 16:57 UTC, joassouza commented on static/js/commentsSetChangeHandler.js
> +commentsSetChangeHandler.prototype._handlePossibleCommentsAddedOrRemovedFromTect = function() {
`Tect`

2019-04-22 16:57 UTC, joassouza commented on static/js/commentsSetChangeHandler.js
> +  this.lastCommentIdsSent = currentCommentIds;
o que você acha de ao invés de `padHasMyChanges` a gente colocasse algo `thisUserChangedPad` (btw, é o nome da função)? Achei que ficou meio complicado entender

2019-04-22 16:57 UTC, joassouza commented on static/js/commentsSetChangeHandler.js
> +  this.lastCommentIdsSent = this.commentDataManager.getCommentIdsStillOnText();
acho que a gente não precisa disso aqui já que a gente faz o mesmo aqui https://github.com/storytouch/ep_comments/pull/58/files#diff-500ef4438a363f450743d4252b99f12eR44
que será chamada logo depois disso

2019-04-22 16:57 UTC, joassouza commented on static/js/index.js
> +exports.handleClientMessage_ACCEPT_COMMIT = function(hook, context) {
```
_etherpad: collab_client.js has a pretty extensive list of message types, if you want to take a look._
é claro que não tem as mensagens separadas em um lugar só, com lindos comentários
```
o que vc acha de adicionar um comentário descrevendo quando esse hook é chamado? 
Como é um dos hooks que a gente usa bem pouco no código, talvez seja mais fácil ler o comentário do que mergulhar no core do Etherpad para entender.

2019-04-22 16:57 UTC, joassouza commented on static/js/index.js
> +exports.handleClientMessage_ACCEPT_COMMIT = function(hook, context) {
dúvida: a gente tem um objeto `hooks` com alguns hooks e outros estão fora desse objeto. Sabe porquê 🤔 ? Por causa disso a gente tem `var thisPlugin = pad.plugins.ep_comments_page;` 2 vezes

2019-04-23 13:57 UTC, lpagliari commented on static/js/commentsSetChangeHandler.js
> +  this.lastCommentIdsSent = currentCommentIds;
não posso ter uma função e uma flag com mesmo nome, uma sobrescreveria a outra

2019-04-23 13:57 UTC, lpagliari commented on static/js/commentsSetChangeHandler.js
> +  this.lastCommentIdsSent = currentCommentIds;
vou tentar pensar em algo

2019-04-23 14:00 UTC, lpagliari commented on static/js/index.js
> +exports.handleClientMessage_ACCEPT_COMMIT = function(hook, context) {
boa!

2019-04-23 14:04 UTC, lpagliari commented on static/js/index.js
> +exports.handleClientMessage_ACCEPT_COMMIT = function(hook, context) {
acho que eram legados, não foram movidos por preguiça nossa mesmo

2019-04-23 14:12 UTC, lpagliari commented on static/js/commentsSetChangeHandler.js
> +  this.lastCommentIdsSent = this.commentDataManager.getCommentIdsStillOnText();
essa função é chamada em outros lugares, não dá para garantir que sempre que chamar uma vai chamar a outra

2019-04-26 13:41 UTC, merged