[feat] Create comment via API
storytouch/ep_comments pull request #59
Opened 2019-05-08 18:27 UTC by joassouza

In this PR we allow to create comment from external sources, like
the App Mananger.

We extracted the code related to line selection from ep_mouse_shortcuts and made a
module on this plugin.
https://github.com/storytouch/ep_mouse_shortcuts/pull/16

2019-05-08 21:38 UTC, lpagliari requested changes
Muito bom PR!

2019-05-08 21:38 UTC, lpagliari commented on static/js/index.js
> +    selectLine.selectLineIfThereIsNoTextSelected(innerAce, rep, caretLine);
sugestão: fazer o último argumento da `selectLineIfThereIsNoTextSelected` ser opcional, e usar `rep.selStart[0]` como `caretLine` se ele não for fornecido. Vai deixar o código mais limpo tb

2019-05-08 21:38 UTC, lpagliari commented on static/js/index.js
> +    },'thisEventWillNotBeCaptured', true);
hum, estamos chamando o `callWithAce` só para ter acesso ao `rep` e ao `editoInfo`, né? Não seria melhor fazer o `bind` da `selectLineIfThereIsNoTextSelected` na `aceInitialized` para limpar um pouco o código?

2019-05-08 21:38 UTC, lpagliari commented on static/tests/frontend/specs/api-showCommentAddDialog.js
> +      $firstLine = helper.padInner$('div').first();
dá para declarar a `$firstLine` aqui dentro, não?

2019-05-08 21:38 UTC, lpagliari commented on static/tests/frontend/specs/api-showCommentAddDialog.js
> +      }, 300);
esse timeout é para deixar a mudança de seleção ser percebida pelo `rep`?

2019-05-08 21:38 UTC, lpagliari commented on static/tests/frontend/specs/api-showCommentAddDialog.js
> +})
esses testes existiam no ep_mouse? Se sim, melhor tirá-los de lá, não? Ou acha que ainda é válido testar se seleciona o texto, etc, etc no outro plugin? (dado que os testes existem aqui, quero dizer)

2019-05-09 14:32 UTC, joassouza commented on static/tests/frontend/specs/api-showCommentAddDialog.js
> +})
sim, acho que vale a pena ter os dois testes. Até por que a chamada do código de seleção fica dentro de cada plugin. Se a gente remover esse código dentro do plugin atualmente o teste gritaria.

Tem umas particularidades com relação a seleção no ep_mouse (desabilita menu).
https://github.com/storytouch/ep_mouse_shortcuts/pull/16/files#diff-fd41383df4389ed6ee75f68becb796d1R87

2019-05-09 14:36 UTC, joassouza commented on static/js/index.js
> +    },'thisEventWillNotBeCaptured', true);
isso aqui eu fiquei na dúvida. É bom por que deixa o código mais limpo mas caso a gente precise usar essa função em outro plugin, a gente acessará a versão `bound` que fica global no editorInfo. E de fato, vou usar a mesma função no ep_touches haha. O que você achar melhor? Deixa necessário o `require` do módulo ou armazena a função `bound` globalmente?

2019-05-09 14:42 UTC, lpagliari commented on static/js/index.js
> +    },'thisEventWillNotBeCaptured', true);
se já vai ter ela _bounded_ no `editorInfo` eu usaria ela diretamente, sem `require`. Já vamos ter que saber que tem coisa fora do `ep_touch` mesmo, então entre o `require` e usar algo já do `editorInfo` eu acho que dá na mesma (sob o ponto de vista de modularidade).

E usando a versão _bounded_ a gente ganha pelo menos a clareza do código...

2019-05-09 17:37 UTC, merged