[feature] Group comment icons
storytouch/ep_comments pull request #88
Opened 2021-07-29 19:26 UTC by vitmf

Group comment icons on the same line similarly to the grouping of tags.
Still needs to correct the CSS.

Implements [card 2800](https://trello.com/c/nmEB3JIi/2800-unificar-%C3%ADcones-de-coment%C3%A1rios-no-et-para-ficar-como-os-%C3%ADcones-de-tags-usando-ellipsis).

2021-08-02 20:34 UTC, ingoncalves requested changes
Belo trabalho @vitmf!

Fiz algumas observações quanto ao estilo do código, pra que a gente consiga manter um código bem padronizado entre os plugins. Com o tempo vc vai pegando esses detalhes. Parabéns!

2021-08-02 20:34 UTC, ingoncalves commented on static/js/commentIcons.js
> +  this._applyGroupStyle($icon, $iconsAtLine)
Faltou um  `;` aqui 
```suggestion
  this._applyGroupStyle($icon, $iconsAtLine);
```

2021-08-02 20:34 UTC, ingoncalves commented on static/js/commentIcons.js
> +  var commentId = "comment-"+$icon.data('commentid');
Nice catch!

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +describe("ep_comments_page - group multiple icons on line", function() {
Acho que você usou o arquivo `test/frontends/specs/commentIcons.js` como base pra construir esse teste. Certo?

O problema é que esse arquivo é bem antigo e está fora dos padrões que temos trabalhado.
Seguem alguns problemas:

- devemos usar aspas simples nas strings
- as funções auxiliares neste arquivo deveriam estar dentro de uma estrutura `helperFunctions`. Veja [static/tests/frontend/specs/commentCopyPaste.js](https://github.com/storytouch/ep_comments/blob/9c11431053d76f1592206bf91d56b5a5e7099aa8/static/tests/frontend/specs/commentCopyPaste.js) como exemplo.
- evitar o uso the `should ...` nas descrições do it

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  context("when comments are on the same line", function(){
```suggestion
  context("when there are more than one comment on the same line", function(){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("should be grouped", function(done){
```suggestion
    it("groups all comment icons on that line", function(done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("first icon should have ellipsis and be visible", function (done) {
```suggestion
    it("sets the first icon as visible and adds an ellipsis to it", function (done) {
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("rest of icons should not have ellipsis and should be hidden", function (done) {
```suggestion
    it("hides the other icons on that line", function (done) {
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  context("when user clicks the SM icon", function () {
```suggestion
  context("when user expands the SM by clicking on the SM icon", function () {
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    context("when user clicks the SM icon again", function () {
```suggestion
    context("and the user collapses the SM", function () {
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +function firstIconIsCorrect($commentLine, done){
```suggestion
function firstIconIsVisibleAndHasEllipsis($commentLine, done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +function otherIconsAreCorrect($commentLine, done){
```suggestion
function otherIconsAreHiddenAndHaveNoEllipsis($commentLine, done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +function commentLineSizeIsCorrect($commentLine, expectedLength, done) {
```suggestion
function commentLineHasNIcons($commentLine, expectedLength, done) {
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +function commentLineIsGroupedCorrectly($commentLine, expectedLength, done){
```suggestion
function commentLineIsGrouped($commentLine, expectedLength, done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("first icon group should remain grouped", function(done){
```suggestion
    it("first icon group remains grouped", function(done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("second icon group should remain grouped", function (done){
```suggestion
    it("second icon group remains grouped", function (done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  context("when comment is deleted in first group", function(){
```suggestion
  context("when a comment is deleted from a group of two icons", function(){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("should ungroup icons", function(done){
```suggestion
    it("removes the ellipsis from the remaining icon", function(done){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  var SECOND_ICON_GROUP = 2; //id of first icon on second group
```suggestion
  var FIRST_ICON_ID = 0; //id of first icon on first group
  var SECOND_ICON_ID = 2; //id of first icon on second group
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  context("when comment is deleted in second group", function(){
```suggestion
  context("when a comment is deleted from a group with more than two icons", function(){
```

2021-08-02 20:34 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("should remain grouped", function(done){
```suggestion
    it("keeps the remaining icons grouped", function(done){
```

2021-08-03 11:04 UTC, WillianGoncalves requested changes
Muito bem! Os testes não são tão fáceis de se fazer, mas você dominou bem. Deixei algumas sugestões para melhorar a leitura. Precisa ajustar algumas descrições de exemplos e nomes de variáveis e funções, o que é bem importante para nos ajudar a entender.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("first icon should have ellipsis and be visible", function (done) {
```suggestion
    it("shows the ellipsis in the first icon", function (done) {
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("rest of icons should not have ellipsis and should be hidden", function (done) {
```suggestion
    it("does not show the other icons", function (done) {
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("first icon group should remain grouped", function(done){
```suggestion
    it("keeps the icons grouped in the first line", function(done){
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("second icon group should remain grouped", function (done){
```suggestion
    it("keeps the icons grouped in the second line", function (done){
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +}
Deve ter sobrado um espaço vazio aqui.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +function getIconOfId(commentId){
Senti um pouco de dificuldade com alguns nomes de função. Por exemplo:

```suggestion
function getCommentIcon(commentId){
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +function getCommentLineOfId(commentId){
```suggestion
function getCommentIconsContainer(commentId){
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +// ----
Aqui você pode remover essas divisões. Não tem problema. Na verdade, fica até mais limpo.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    it("should be grouped", function(done){
```suggestion
    it("groups the comment icons", function(done){
```

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +      commentLineSizeIsCorrect($commentLine, FIRST_GROUP_LENGTH, done);
Extrair o código do teste em uma função pode não ser uma boa idéia, porque o que está sendo testado fica escondido da descrição do exemplo (`it(...)`). Para evitar esse tipo de problema, mantenha o código dentro do `it`.
Em alguns lugares, quando um mesmo exemplo é repetido em diferentes cenários, a gente move todo o exemplo para uma função. Veja o `commentIcons.js`, na mesma pasta que esse arquivo. Ele tem uma função `testIfCaretIsAtBeginningOfCommentedText` que define o exemplo (`it`) e o código do teste dentro dele. Assim a gente consegue identificar de imediato quais propriedades estamos usando pra fazer a verificação.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +      firstIconIsCorrect($commentLine, done);
Esse aqui é outro caso. Pense no seguinte: o que significa "first icon is correct"? Isso depende do contexto e do exemplo que estamos definindo. Portanto, seria melhor trazer o código dessa função pra cá.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +      otherIconsAreCorrect($commentLine, done);
O mesmo caso aqui.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  var SECOND_ICON_GROUP = 2; //id of first icon on second group
Esses nomes não estão legais. Estão causando um pouco de confusão para quem lê o teste. Pelo nome eu esperava "o primeiro grupo de ícones", o que também não faz muito sentido. Mas o comentário diz que é o id do primeiro ícone no primeiro grupo.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +    commentIds = utils.getCommentIdsOnText();
Essa linha pode ir direto na 43. Não precisa dessa função `getCommentsIds`.

2021-08-03 11:04 UTC, WillianGoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +      }).done(done);
Esse bloco ficou um pouco confuso, mais por causa dos nomes das variáveis e funções.

2021-08-10 14:57 UTC, WillianGoncalves requested changes

2021-08-10 14:57 UTC, WillianGoncalves commented on static/js/commentIcons.js
> +    }
Aqui vale a mesma sugestão feita em:

https://github.com/storytouch/ep_script_touches/pull/114/files#r686048669

2021-08-11 15:31 UTC, ingoncalves requested changes

2021-08-11 15:31 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +ep_comments_page_test_helper.commentIcons = {
Como `ep_comments_page_test_helper.commentIcons` já foi definido no outro arquivo de testes, precisamos renomear aqui pra evitar algum conflito quando todos os testes são executados juntos.

```suggestion
ep_comments_page_test_helper.commentIconsGroups = {
```

2021-08-11 15:31 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  };
Essas duas funções também podem ir pra dentro de `ep_comments_page_test_helper.commentIconsGroups`.

2021-08-11 15:31 UTC, ingoncalves commented on static/tests/frontend/specs/commentIconsGroups.js
> +  var apiUtils = ep_comments_page_test_helper.apiUtils;
Aqui pode só declarar a variável, como vc fez com `helperFunctions`. Deixa pra assinar o valor dentro do `before`. Isso tem um motivio, pois esses valores nem sempre estão disponíveis antes de começar o teste. Fazendo a assinatura dentro do primeiro `before`, a gente tem certeza que tá tudo inicializado corretamente.

2021-08-13 19:18 UTC, merged